version: '3.1'

volumes:
  data:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 102030Tjs!
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data